# -*- coding: utf-8 -*-
"""totalsales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13e3bRJJoyIqXLTJnlxNvbDtBdfnHZuHi
"""



import pandas as pd

# Load the CSV file
df_sales = pd.read_csv('/content/drive/MyDrive/sales_data.csv')

# Calculate total sales for each product
df_sales['total_sales'] = df_sales['quantity'] * df_sales['price']
total_sales_per_product = df_sales.groupby('product_id')['total_sales'].sum().reset_index()

# Identify the top 5 products with the highest sales
top_5_products = total_sales_per_product.sort_values(by='total_sales', ascending=False).head(5)

# Generate a summary report in a new CSV file
summary_file_path = '/content/top_5_products_sales_summary.csv'
top_5_products.to_csv(summary_file_path, index=False)

